export interface QuizQuestion {
  id: string;
  subject: "Physics" | "Mathematics" | "Computer Science" | "Chemistry" | "Biology" | "World History";
  topic: string;
  question: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
}

export const SUBJECT_ICONS: Record<QuizQuestion["subject"], string> = {
  Physics: "⚡",
  Mathematics: "📐",
  "Computer Science": "💻",
  Chemistry: "🧪",
  Biology: "🧬",
  "World History": "🏛️",
};

export const QUIZ_BANK: QuizQuestion[] = [
  // ─── PHYSICS (18 Questions) ───
  {
    id: "phy-1",
    subject: "Physics",
    topic: "Mechanics",
    question: "What happens to the terminal velocity of a falling sphere if its radius is doubled (assuming laminar Stokes flow)?",
    options: ["It remains unchanged", "It doubles", "It quadruples (4x)", "It increases by 8x"],
    correctIndex: 2,
    explanation: "In Stokes flow, drag force F_d = 6πηrv and gravitational force F_g ∝ r³. Equating gives v_t ∝ r², so doubling radius quadruples terminal velocity.",
    difficulty: "hard",
  },
  {
    id: "phy-2",
    subject: "Physics",
    topic: "Thermodynamics",
    question: "In an adiabatic expansion of an ideal gas, which of the following is true regarding work done and internal energy?",
    options: ["W > 0 and ΔU < 0", "W > 0 and ΔU > 0", "W < 0 and ΔU = 0", "W = 0 and ΔU = 0"],
    correctIndex: 0,
    explanation: "In an adiabatic process, Q = 0. By First Law ΔU = Q - W = -W. Expansion means W > 0, so ΔU must be negative (gas cools).",
    difficulty: "medium",
  },
  {
    id: "phy-3",
    subject: "Physics",
    topic: "Electromagnetism",
    question: "Lenz's Law is a direct consequence of which fundamental conservation law?",
    options: ["Conservation of Charge", "Conservation of Momentum", "Conservation of Energy", "Conservation of Angular Momentum"],
    correctIndex: 2,
    explanation: "Lenz's Law states induced EMF opposes the change creating it. If it aided the change, perpetual energy would be created violating Conservation of Energy.",
    difficulty: "easy",
  },
  {
    id: "phy-4",
    subject: "Physics",
    topic: "Optics",
    question: "Total internal reflection occurs only when light passes from:",
    options: ["A rarer to a denser medium at any angle", "A denser to a rarer medium at an angle greater than critical angle", "A denser to a rarer medium at an angle less than critical angle", "Vacuum into a medium with refractive index > 1"],
    correctIndex: 1,
    explanation: "Light bends away from normal entering a rarer medium. When the incident angle exceeds the critical angle, refraction is impossible and total internal reflection occurs.",
    difficulty: "easy",
  },
  {
    id: "phy-5",
    subject: "Physics",
    topic: "Quantum Physics",
    question: "In the photoelectric effect, increasing the intensity of incident light increases:",
    options: ["Maximum kinetic energy of photoelectrons", "Threshold frequency of the metal", "The rate of emitted photoelectrons (current)", "The stopping potential"],
    correctIndex: 2,
    explanation: "Higher intensity means more photons per second, thus ejecting more photoelectrons per second (higher photocurrent). Kinetic energy depends solely on photon frequency.",
    difficulty: "medium",
  },
  {
    id: "phy-6",
    subject: "Physics",
    topic: "Gravitation",
    question: "If Earth compressed to half its current radius while keeping mass constant, the acceleration due to gravity on the surface would:",
    options: ["Halve", "Double", "Quadruple (4x)", "Remain unchanged"],
    correctIndex: 2,
    explanation: "g = GM/R². If R becomes R/2, g' = GM / (R/2)² = 4 * (GM/R²) = 4g.",
    difficulty: "easy",
  },
  {
    id: "phy-7",
    subject: "Physics",
    topic: "Wave Motion",
    question: "When a sound wave travels from air into water, which wave characteristic remains strictly constant?",
    options: ["Wavelength", "Speed", "Frequency", "Amplitude"],
    correctIndex: 2,
    explanation: "Frequency is determined solely by the source of vibration. When entering a new medium, speed and wavelength change proportionally (v = fλ), but frequency stays constant.",
    difficulty: "easy",
  },
  {
    id: "phy-8",
    subject: "Physics",
    topic: "Nuclear Physics",
    question: "Which type of radioactive decay produces a daughter nucleus with the same mass number but an atomic number increased by 1?",
    options: ["Alpha decay", "Beta-minus (β⁻) decay", "Beta-plus (β⁺) decay", "Gamma decay"],
    correctIndex: 1,
    explanation: "In beta-minus decay, a neutron transforms into a proton, emitting an electron and an electron antineutrino: n → p + e⁻ + ν̄_e.",
    difficulty: "medium",
  },
  {
    id: "phy-9",
    subject: "Physics",
    topic: "Special Relativity",
    question: "According to special relativity, as an object's speed approaches the speed of light (c), its observed length along the direction of motion:",
    options: ["Approaches infinity", "Contracts toward zero", "Expands perpendicularly", "Stays strictly invariant"],
    correctIndex: 1,
    explanation: "Lorentz contraction formula L = L₀ √(1 - v²/c²) shows that as v → c, the relativistic factor approaches 0, contracting length along motion toward zero.",
    difficulty: "medium",
  },
  {
    id: "phy-10",
    subject: "Physics",
    topic: "Rotational Dynamics",
    question: "A solid sphere and a hollow cylinder of equal mass and radius roll down an incline without slipping. Which reaches the bottom first?",
    options: ["The hollow cylinder", "The solid sphere", "Both reach simultaneously", "Depends on incline angle"],
    correctIndex: 1,
    explanation: "The solid sphere has a lower moment of inertia (I = 2/5 MR²) compared to the hollow cylinder (I = MR²), leaving more gravitational energy for translational kinetic energy.",
    difficulty: "medium",
  },
  {
    id: "phy-11",
    subject: "Physics",
    topic: "Fluid Dynamics",
    question: "Bernoulli's principle for streamline fluid flow is essentially an expression of:",
    options: ["Conservation of mass", "Conservation of momentum", "Conservation of energy", "Newton's third law"],
    correctIndex: 2,
    explanation: "Bernoulli's equation P + 1/2ρv² + ρgh = constant represents conservation of mechanical energy per unit volume in an incompressible, non-viscous fluid.",
    difficulty: "easy",
  },
  {
    id: "phy-12",
    subject: "Physics",
    topic: "Oscillations",
    question: "For a simple pendulum executing SHM, if the mass of the bob is tripled, its time period:",
    options: ["Triples", "Increases by √3", "Remains unchanged", "Decreases by 1/3"],
    correctIndex: 2,
    explanation: "The time period of a simple pendulum is T = 2π√(L/g), which is completely independent of the mass of the oscillating bob.",
    difficulty: "easy",
  },
  {
    id: "phy-13",
    subject: "Physics",
    topic: "Electrodynamics",
    question: "The displacement current introduced by Maxwell into Ampère's circuital law accounts for:",
    options: ["Conduction in superconductors", "Time-varying electric flux between capacitor plates", "Eddy currents in iron cores", "Thermal electron emissions"],
    correctIndex: 1,
    explanation: "Maxwell recognized that a time-changing electric flux between capacitor plates generates a magnetic field, formulated as displacement current I_d = ε₀(dΦ_E/dt).",
    difficulty: "hard",
  },
  {
    id: "phy-14",
    subject: "Physics",
    topic: "Thermodynamics",
    question: "The maximum theoretical efficiency of a heat engine operating between 600 K and 300 K is:",
    options: ["25%", "50%", "75%", "100%"],
    correctIndex: 1,
    explanation: "Carnot efficiency η = 1 - (T_cold / T_hot) = 1 - (300 / 600) = 0.50 (50%).",
    difficulty: "easy",
  },
  {
    id: "phy-15",
    subject: "Physics",
    topic: "Modern Physics",
    question: "The de Broglie wavelength associated with a particle is inversely proportional to its:",
    options: ["Energy", "Linear momentum", "Velocity squared", "Rest mass only"],
    correctIndex: 1,
    explanation: "de Broglie relation λ = h / p states wavelength is inversely proportional to linear momentum p = mv.",
    difficulty: "easy",
  },
  {
    id: "phy-16",
    subject: "Physics",
    topic: "Superconductivity",
    question: "The complete expulsion of magnetic flux lines from the interior of a superconductor is known as:",
    options: ["Hall effect", "Meissner effect", "Zeeman effect", "Seebeck effect"],
    correctIndex: 1,
    explanation: "The Meissner effect describes how superconductors below their critical temperature actively expel magnetic fields, showing perfect diamagnetism.",
    difficulty: "medium",
  },
  {
    id: "phy-17",
    subject: "Physics",
    topic: "Optics",
    question: "Which phenomenon confirms the transverse nature of electromagnetic light waves?",
    options: ["Interference", "Diffraction", "Polarization", "Refraction"],
    correctIndex: 2,
    explanation: "Only transverse waves can be polarized. Longitudinal waves (like sound in air) cannot exhibit polarization.",
    difficulty: "easy",
  },
  {
    id: "phy-18",
    subject: "Physics",
    topic: "Astrophysics",
    question: "The Chandrasekhar limit (~1.4 solar masses) represents the maximum mass for a stable:",
    options: ["Neutron star", "White dwarf", "Black hole", "Red giant"],
    correctIndex: 1,
    explanation: "Electron degeneracy pressure can support a white dwarf star only up to ~1.44 solar masses; beyond this, it collapses into a neutron star or black hole.",
    difficulty: "hard",
  },

  // ─── MATHEMATICS (18 Questions) ───
  {
    id: "math-1",
    subject: "Mathematics",
    topic: "Calculus",
    question: "What is the derivative of f(x) = x^x for x > 0?",
    options: ["x * x^(x-1)", "x^x * ln(x)", "x^x * (1 + ln(x))", "e^x * (1 + ln(x))"],
    correctIndex: 2,
    explanation: "Using logarithmic differentiation: y = x^x → ln(y) = x ln(x) → y'/y = ln(x) + 1 → y' = x^x (1 + ln(x)).",
    difficulty: "medium",
  },
  {
    id: "math-2",
    subject: "Mathematics",
    topic: "Linear Algebra",
    question: "If matrix A is invertible and λ is an eigenvalue of A, what is an eigenvalue of A⁻¹?",
    options: ["-λ", "1/λ", "λ²", "√λ"],
    correctIndex: 1,
    explanation: "Av = λv. Multiplying by A⁻¹ gives v = λ A⁻¹v → A⁻¹v = (1/λ)v, meaning 1/λ is an eigenvalue of A⁻¹.",
    difficulty: "easy",
  },
  {
    id: "math-3",
    subject: "Mathematics",
    topic: "Probability",
    question: "In a standard deck of 52 cards, what is the probability of drawing either an Ace or a Heart?",
    options: ["17/52", "16/52 (4/13)", "13/52", "4/52"],
    correctIndex: 1,
    explanation: "P(Ace ∪ Heart) = P(Ace) + P(Heart) - P(Ace ∩ Heart) = 4/52 + 13/52 - 1/52 = 16/52 = 4/13.",
    difficulty: "easy",
  },
  {
    id: "math-4",
    subject: "Mathematics",
    topic: "Differential Equations",
    question: "The general solution to the ordinary differential equation y'' + 9y = 0 is:",
    options: ["y = C₁ e^(3x) + C₂ e^(-3x)", "y = C₁ cos(3x) + C₂ sin(3x)", "y = (C₁ + C₂ x)e^(3x)", "y = C₁ cosh(3x) + C₂ sinh(3x)"],
    correctIndex: 1,
    explanation: "The characteristic equation r² + 9 = 0 yields imaginary roots r = ±3i. The general solution is y = C₁ cos(3x) + C₂ sin(3x).",
    difficulty: "medium",
  },
  {
    id: "math-5",
    subject: "Mathematics",
    topic: "Complex Numbers",
    question: "What is the principal value of i^i where i = √(-1)?",
    options: ["-1", "e^(π/2)", "e^(-π/2)", "i e^(-π)"],
    correctIndex: 2,
    explanation: "i = e^(i π/2). Therefore i^i = (e^(i π/2))^i = e^(i² π/2) = e^(-π/2) ≈ 0.2078 (a purely real number!).",
    difficulty: "hard",
  },
  {
    id: "math-6",
    subject: "Mathematics",
    topic: "Discrete Math",
    question: "How many distinct permutations can be made from the letters of the word 'SUCCESS'?",
    options: ["5040", "420", "210", "840"],
    correctIndex: 1,
    explanation: "Total 7 letters with 3 S's and 2 C's: 7! / (3! * 2!) = 5040 / (6 * 2) = 420.",
    difficulty: "medium",
  },
  {
    id: "math-7",
    subject: "Mathematics",
    topic: "Calculus",
    question: "What is the value of the definite integral ∫ (from 0 to ∞) of e^(-x²) dx?",
    options: ["1", "√π / 2", "π / 2", "√π"],
    correctIndex: 1,
    explanation: "This is the classic Gaussian integral. The integral over (-∞, ∞) is √π, so the symmetric half from 0 to ∞ is √π / 2.",
    difficulty: "hard",
  },
  {
    id: "math-8",
    subject: "Mathematics",
    topic: "Graph Theory",
    question: "According to Euler's formula for any connected planar graph with V vertices, E edges, and F faces:",
    options: ["V - E + F = 2", "V + E - F = 2", "V - E - F = 1", "2V - E + F = 0"],
    correctIndex: 0,
    explanation: "Euler's planar graph formula states V - E + F = 2 (where F includes the unbounded outer face).",
    difficulty: "easy",
  },
  {
    id: "math-9",
    subject: "Mathematics",
    topic: "Number Theory",
    question: "Fermat's Little Theorem states that if p is prime and gcd(a, p) = 1, then:",
    options: ["a^p ≡ a (mod p)", "a^(p-1) ≡ 1 (mod p)", "a^(p+1) ≡ 0 (mod p)", "p^(a-1) ≡ 1 (mod a)"],
    correctIndex: 1,
    explanation: "Fermat's Little Theorem: a^(p-1) ≡ 1 (mod p) for any integer a coprime to prime p.",
    difficulty: "medium",
  },
  {
    id: "math-10",
    subject: "Mathematics",
    topic: "Linear Algebra",
    question: "The trace of a square matrix equals the sum of its:",
    options: ["Row elements", "Eigenvalues", "Singular values squared", "Determinants of submatrices"],
    correctIndex: 1,
    explanation: "The trace Tr(A) = ∑ A_ii equals the sum of all eigenvalues λ₁ + λ₂ + ... + λ_n with algebraic multiplicity.",
    difficulty: "easy",
  },
  {
    id: "math-11",
    subject: "Mathematics",
    topic: "Sequences & Series",
    question: "The infinite series ∑ (from n=1 to ∞) of 1/n^p converges if and only if:",
    options: ["p ≥ 1", "p > 1", "p > 0", "p ≥ 2"],
    correctIndex: 1,
    explanation: "By the p-series test, ∑ 1/n^p converges strictly when p > 1 and diverges for p ≤ 1 (e.g. harmonic series p=1 diverges).",
    difficulty: "easy",
  },
  {
    id: "math-12",
    subject: "Mathematics",
    topic: "Set Theory",
    question: "Cantor's diagonal argument proves that the set of real numbers [0, 1] is:",
    options: ["Countably infinite", "Uncountably infinite", "Finite", "Algebraic"],
    correctIndex: 1,
    explanation: "Cantor constructed a real number differing from every indexed element at the n-th decimal place, proving reals cannot be put in 1-to-1 bijection with natural numbers.",
    difficulty: "medium",
  },
  {
    id: "math-13",
    subject: "Mathematics",
    topic: "Calculus",
    question: "The Maclaurin series expansion for cos(x) begins with:",
    options: ["x - x³/6 + x⁵/120 - ...", "1 - x²/2! + x⁴/4! - ...", "1 + x²/2! + x⁴/4! + ...", "x + x³/3! + x⁵/5! + ..."],
    correctIndex: 1,
    explanation: "cos(x) is an even function with alternating signs for even powers: 1 - x²/2 + x⁴/24 - x⁶/720 + ...",
    difficulty: "easy",
  },
  {
    id: "math-14",
    subject: "Mathematics",
    topic: "Topology",
    question: "A topological space is called 'compact' if:",
    options: ["Every sequence converges to a unique point", "Every open cover has a finite subcover", "It is both open and closed", "It has no boundary points"],
    correctIndex: 1,
    explanation: "The standard definition of compactness is that every open cover admits a finite subcover.",
    difficulty: "hard",
  },
  {
    id: "math-15",
    subject: "Mathematics",
    topic: "Statistics",
    question: "The Central Limit Theorem asserts that the sample mean distribution approaches normal distribution as sample size n increases, provided:",
    options: ["The population is already normal", "Samples are independent with finite variance", "Variance equals the mean", "The sample size is exactly 30"],
    correctIndex: 1,
    explanation: "CLT applies to independent, identically distributed variables with finite mean and finite variance, regardless of the underlying population shape.",
    difficulty: "medium",
  },
  {
    id: "math-16",
    subject: "Mathematics",
    topic: "Vectors",
    question: "For two 3D vectors A and B, |A × B|² + (A · B)² equals:",
    options: ["|A|² + |B|²", "|A|² |B|²", "2|A| |B|", "0"],
    correctIndex: 1,
    explanation: "(|A||B|sinθ)² + (|A||B|cosθ)² = |A|²|B|²(sin²θ + cos²θ) = |A|²|B|².",
    difficulty: "easy",
  },
  {
    id: "math-17",
    subject: "Mathematics",
    topic: "Combinatorics",
    question: "What is the coefficient of x³ y⁴ in the binomial expansion of (2x - y)⁷?",
    options: ["-280", "280", "-70", "560"],
    correctIndex: 1,
    explanation: "Term is (7 choose 3) * (2x)³ * (-y)⁴ = 35 * 8x³ * y⁴ = 280 x³ y⁴.",
    difficulty: "medium",
  },
  {
    id: "math-18",
    subject: "Mathematics",
    topic: "Calculus",
    question: "What is the limit of (sin x) / x as x approaches 0?",
    options: ["0", "1", "Undefined", "Infinity"],
    correctIndex: 1,
    explanation: "By L'Hôpital's rule or geometric squeeze theorem, lim(x→0) sin(x)/x = cos(0)/1 = 1.",
    difficulty: "easy",
  },

  // ─── COMPUTER SCIENCE (18 Questions) ───
  {
    id: "cs-1",
    subject: "Computer Science",
    topic: "Data Structures",
    question: "What is the worst-case time complexity of searching for an element in a balanced Red-Black Tree with n nodes?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 1,
    explanation: "Red-Black trees maintain a maximum height of 2 * log₂(n + 1), guaranteeing O(log n) worst-case search, insertion, and deletion.",
    difficulty: "easy",
  },
  {
    id: "cs-2",
    subject: "Computer Science",
    topic: "Algorithms",
    question: "Dijkstra's shortest path algorithm fails to yield optimal results when:",
    options: ["Graphs contain directed cycles", "Graphs contain edges with negative weights", "Graphs have disconnected components", "Vertices have non-zero in-degrees"],
    correctIndex: 1,
    explanation: "Dijkstra's greedy assumption assumes visiting a node finalizes its shortest path; negative edge weights invalidate this, requiring the Bellman-Ford algorithm.",
    difficulty: "medium",
  },
  {
    id: "cs-3",
    subject: "Computer Science",
    topic: "Computer Architecture",
    question: "Which cache mapping technique allows a memory block to be placed in any cache line?",
    options: ["Direct Mapped", "Fully Associative", "Set Associative", "Snooping Cache"],
    correctIndex: 1,
    explanation: "Fully Associative cache allows memory blocks to reside in any cache slot, eliminating conflict misses at the expense of more complex comparator hardware.",
    difficulty: "medium",
  },
  {
    id: "cs-4",
    subject: "Computer Science",
    topic: "Operating Systems",
    question: "Which of the following is NOT one of the four Coffman conditions necessary for deadlock?",
    options: ["Mutual Exclusion", "Hold and Wait", "Preemption Allowed", "Circular Wait"],
    correctIndex: 2,
    explanation: "The condition is 'No Preemption' (resources cannot be forcibly taken). If preemption is allowed, deadlock cannot occur.",
    difficulty: "easy",
  },
  {
    id: "cs-5",
    subject: "Computer Science",
    topic: "Databases",
    question: "In ACID transaction properties, which property ensures transactions that commit survive system crashes?",
    options: ["Atomicity", "Consistency", "Isolation", "Durability"],
    correctIndex: 3,
    explanation: "Durability guarantees that once a transaction has committed, its updates are recorded in non-volatile storage (WAL/disk) and survive crashes.",
    difficulty: "easy",
  },
  {
    id: "cs-6",
    subject: "Computer Science",
    topic: "Networking",
    question: "In the TCP 3-way handshake to establish a connection, the sequence of packets exchanged is:",
    options: ["SYN -> ACK -> SYN-ACK", "SYN -> SYN-ACK -> ACK", "ACK -> SYN -> ACK-SYN", "FIN -> ACK -> FIN-ACK"],
    correctIndex: 1,
    explanation: "Client sends SYN, Server replies with SYN-ACK, Client acknowledges with ACK, transitioning the socket to ESTABLISHED.",
    difficulty: "easy",
  },
  {
    id: "cs-7",
    subject: "Computer Science",
    topic: "Complexity Theory",
    question: "A problem is defined as NP-Complete if it belongs to NP and:",
    options: ["It can be solved in O(n²) time", "Every problem in NP can be polynomial-time reduced to it", "It is undecidable", "Its complement is in P"],
    correctIndex: 1,
    explanation: "By definition, a problem is NP-Complete if (1) it is in NP and (2) it is NP-Hard (all problems in NP reduce to it in polynomial time).",
    difficulty: "hard",
  },
  {
    id: "cs-8",
    subject: "Computer Science",
    topic: "Programming Languages",
    question: "What does 'closure' mean in modern JavaScript / functional programming?",
    options: ["A function that automatically terminates recursion", "A function combined with references to its surrounding lexical environment", "An asynchronous callback promise", "A method for private class encapsulation"],
    correctIndex: 1,
    explanation: "A closure is the combination of a function bundled together with references to its surrounding state (lexical environment), allowing access to outer scope variables even after execution.",
    difficulty: "easy",
  },
  {
    id: "cs-9",
    subject: "Computer Science",
    topic: "Algorithms",
    question: "What is the average and worst-case time complexity of QuickSelect to find the k-th smallest element in an array?",
    options: ["Average O(n), Worst O(n²)", "Average O(n log n), Worst O(n²)", "Average O(log n), Worst O(n)", "Average O(n), Worst O(n)"],
    correctIndex: 0,
    explanation: "QuickSelect recurses into only one partition half, giving T(n) = n + n/2 + n/4... = O(n) average, but O(n²) if unbalanced pivots are chosen without median-of-medians.",
    difficulty: "hard",
  },
  {
    id: "cs-10",
    subject: "Computer Science",
    topic: "Security & Cryptography",
    question: "RSA public-key cryptography relies fundamentally on the mathematical computational difficulty of:",
    options: ["Discrete logarithms on elliptic curves", "Factoring large semiprime integers", "Finding collision pre-images in SHA-256", "Inverting non-singular matrix transformations"],
    correctIndex: 1,
    explanation: "RSA's one-way trapdoor function is based on the ease of multiplying two prime numbers (p * q) vs the extreme difficulty of prime factorization of large product N.",
    difficulty: "medium",
  },
  {
    id: "cs-11",
    subject: "Computer Science",
    topic: "Distributed Systems",
    question: "According to Eric Brewer's CAP theorem, a distributed data store can guarantee at most how many properties simultaneously?",
    options: ["1 of 3", "2 of 3 (Consistency, Availability, Partition Tolerance)", "All 3 with Raft consensus", "3 of 4 including Durability"],
    correctIndex: 1,
    explanation: "In the presence of network partitions (P), a distributed system must choose between Consistency (C) and Availability (A).",
    difficulty: "medium",
  },
  {
    id: "cs-12",
    subject: "Computer Science",
    topic: "Data Structures",
    question: "Which data structure is primarily utilized to implement Breadth-First Search (BFS) on a graph?",
    options: ["Stack", "Queue (FIFO)", "Priority Queue / Heap", "Hash Table"],
    correctIndex: 1,
    explanation: "BFS explores nodes level by level in First-In-First-Out order, naturally implemented with a Queue.",
    difficulty: "easy",
  },
  {
    id: "cs-13",
    subject: "Computer Science",
    topic: "Operating Systems",
    question: "Virtual memory systems use a Translation Lookaside Buffer (TLB) specifically to:",
    options: ["Store executable binaries", "Cache recent virtual-to-physical address page translations", "Manage disk swap partitions", "Arbitrate DMA requests"],
    correctIndex: 1,
    explanation: "The TLB is a high-speed hardware memory cache that holds recent mappings from virtual page numbers to physical frame numbers to avoid page table walk latencies.",
    difficulty: "medium",
  },
  {
    id: "cs-14",
    subject: "Computer Science",
    topic: "Algorithms",
    question: "In Dynamic Programming, the optimal substructure property means that:",
    options: ["All subproblems overlap identically", "An optimal solution to the problem contains optimal solutions to subproblems", "Greedy choices lead to the global maximum", "Recursion depth is bounded by O(log n)"],
    correctIndex: 1,
    explanation: "Optimal substructure ensures the global optimal solution can be constructed efficiently from the optimal solutions of its subproblems.",
    difficulty: "medium",
  },
  {
    id: "cs-15",
    subject: "Computer Science",
    topic: "Web Architecture",
    question: "What HTTP status code represents '401' vs '403'?",
    options: ["401: Forbidden, 403: Unauthorized", "401: Unauthorized (Unauthenticated), 403: Forbidden (Authenticated but lacking permissions)", "401: Not Found, 403: Bad Gateway", "401: Method Not Allowed, 403: Timeout"],
    correctIndex: 1,
    explanation: "401 means credentials are missing/invalid. 403 means the server understands identity but refuses to authorize the requested action.",
    difficulty: "easy",
  },
  {
    id: "cs-16",
    subject: "Computer Science",
    topic: "Data Structures",
    question: "What is the amortized insertion time complexity for a dynamic array (like std::vector or ArrayList)?",
    options: ["O(n)", "O(1)", "O(log n)", "O(n²)"],
    correctIndex: 1,
    explanation: "Doubling array capacity when full incurs O(n) reallocation occasionally, but dividing total copy cost over n insertions yields O(1) amortized time per append.",
    difficulty: "easy",
  },
  {
    id: "cs-17",
    subject: "Computer Science",
    topic: "Machine Learning",
    question: "In deep learning, the 'vanishing gradient problem' is commonly mitigated by using which activation function instead of Sigmoid?",
    options: ["Step Function", "Rectified Linear Unit (ReLU)", "Softmax", "Signum"],
    correctIndex: 1,
    explanation: "ReLU has a constant gradient of 1 for positive inputs, preventing gradients from decaying exponentially across deep layers.",
    difficulty: "medium",
  },
  {
    id: "cs-18",
    subject: "Computer Science",
    topic: "Algorithms",
    question: "Which sorting algorithm is guaranteed to be stable and has a worst-case time complexity of O(n log n)?",
    options: ["QuickSort", "HeapSort", "MergeSort", "SelectionSort"],
    correctIndex: 2,
    explanation: "MergeSort always divides and merges in O(n log n) worst-case time and preserves the relative order of duplicate keys (stable).",
    difficulty: "easy",
  },

  // ─── CHEMISTRY (16 Questions) ───
  {
    id: "chem-1",
    subject: "Chemistry",
    topic: "Chemical Bonding",
    question: "What is the hybridization and molecular geometry of Xenon Tetrafluoride (XeF₄)?",
    options: ["sp³d, Seesaw", "sp³d², Square Planar", "sp³d², Octahedral", "sp³d³, Pentagonal Planar"],
    correctIndex: 1,
    explanation: "Xe has 8 valence electrons. With 4 bonding pairs and 2 lone pairs (steric number 6), hybridization is sp³d² with square planar molecular geometry.",
    difficulty: "medium",
  },
  {
    id: "chem-2",
    subject: "Chemistry",
    topic: "Thermodynamics",
    question: "A chemical reaction is spontaneous at all temperatures if:",
    options: ["ΔH > 0 and ΔS > 0", "ΔH < 0 and ΔS > 0", "ΔH < 0 and ΔS < 0", "ΔH > 0 and ΔS < 0"],
    correctIndex: 1,
    explanation: "Gibbs equation ΔG = ΔH - TΔS. If ΔH is negative (exothermic) and ΔS is positive (entropy increases), ΔG is strictly negative at every temperature.",
    difficulty: "easy",
  },
  {
    id: "chem-3",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    question: "An SN2 substitution reaction proceeds with:",
    options: ["Complete retention of configuration", "Complete inversion of configuration (Walden inversion)", "Racemization (50/50 mixture)", "Carbocation intermediate rearrangement"],
    correctIndex: 1,
    explanation: "SN2 features backside nucleophilic attack in a concerted single step, inverting stereochemistry like an umbrella blown inside out.",
    difficulty: "medium",
  },
  {
    id: "chem-4",
    subject: "Chemistry",
    topic: "Electrochemistry",
    question: "According to the Nernst equation, increasing the concentration of reaction products in a galvanic cell will:",
    options: ["Increase cell potential (E_cell)", "Decrease cell potential (E_cell)", "Have zero effect on E_cell", "Invert the cathode and anode roles"],
    correctIndex: 1,
    explanation: "E = E° - (RT/nF) ln(Q). Increasing product concentration increases reaction quotient Q, making the subtracted term larger, thus decreasing cell potential.",
    difficulty: "medium",
  },
  {
    id: "chem-5",
    subject: "Chemistry",
    topic: "Periodic Trends",
    question: "Which element possesses the highest first ionization energy?",
    options: ["Helium (He)", "Fluorine (F)", "Neon (Ne)", "Hydrogen (H)"],
    correctIndex: 0,
    explanation: "Helium has a 1s² full valence shell closest to the nucleus with minimal shielding, resulting in the highest ionization energy (~2372 kJ/mol) of all elements.",
    difficulty: "easy",
  },
  {
    id: "chem-6",
    subject: "Chemistry",
    topic: "Equilibrium",
    question: "For the exothermic Haber process N₂ + 3H₂ ⇌ 2NH₃ (ΔH = -92 kJ), Le Chatelier's principle predicts that raising the temperature will:",
    options: ["Shift equilibrium right (increase NH₃)", "Shift equilibrium left (decrease NH₃)", "Leave equilibrium concentrations unaffected", "Double the equilibrium constant K_eq"],
    correctIndex: 1,
    explanation: "Since the reaction releases heat, adding heat shifts the equilibrium in the endothermic reverse direction, reducing ammonia yield.",
    difficulty: "easy",
  },
  {
    id: "chem-7",
    subject: "Chemistry",
    topic: "Kinetics",
    question: "For a second-order reaction, a plot of which variables yields a straight line with slope equal to the rate constant k?",
    options: ["ln[A] vs time t", "1/[A] vs time t", "[A] vs time t", "ln(k) vs 1/T"],
    correctIndex: 1,
    explanation: "The integrated second-order rate law is 1/[A]_t = 1/[A]_0 + kt, giving a linear plot of 1/[A] vs t with slope +k.",
    difficulty: "medium",
  },
  {
    id: "chem-8",
    subject: "Chemistry",
    topic: "Acids and Bases",
    question: "What is the pH of a 0.001 M solution of strong hydrochloric acid (HCl) at 25°C?",
    options: ["1", "2", "3", "11"],
    correctIndex: 2,
    explanation: "HCl fully dissociates: [H⁺] = 10⁻³ M. pH = -log₁₀[H⁺] = -log₁₀(10⁻³) = 3.",
    difficulty: "easy",
  },
  {
    id: "chem-9",
    subject: "Chemistry",
    topic: "Coordination Chemistry",
    question: "What is the coordination number and oxidation state of cobalt in [Co(NH₃)₅Cl]Cl₂?",
    options: ["Coordination number 6, Oxidation state +3", "Coordination number 5, Oxidation state +2", "Coordination number 6, Oxidation state +2", "Coordination number 4, Oxidation state +3"],
    correctIndex: 0,
    explanation: "Inside brackets there are 5 NH₃ + 1 Cl⁻ = 6 ligands (coordination number 6). Counter ions are 2 Cl⁻ (-2) and ligand Cl⁻ (-1), making Co state +3.",
    difficulty: "medium",
  },
  {
    id: "chem-10",
    subject: "Chemistry",
    topic: "States of Matter",
    question: "Real gases deviate most from ideal gas behavior under which set of conditions?",
    options: ["High temperature and low pressure", "Low temperature and high pressure", "High temperature and high pressure", "Low temperature and low pressure"],
    correctIndex: 1,
    explanation: "At low temperatures intermolecular forces become significant, and at high pressures particle volume is no longer negligible compared to total volume.",
    difficulty: "easy",
  },
  {
    id: "chem-11",
    subject: "Chemistry",
    topic: "Organic Chemistry",
    question: "The conversion of an alkene to an alcohol using BH₃ followed by H₂O₂/NaOH is known as:",
    options: ["Markovnikov hydration", "Anti-Markovnikov hydroboration-oxidation", "Oxymercuration-demercuration", "Ozonolysis"],
    correctIndex: 1,
    explanation: "Hydroboration-oxidation yields anti-Markovnikov syn-addition of water across double bonds without carbocation rearrangement.",
    difficulty: "medium",
  },
  {
    id: "chem-12",
    subject: "Chemistry",
    topic: "Nuclear Chemistry",
    question: "Which isotope of carbon is widely used in radiocarbon dating of organic archaeological artifacts?",
    options: ["Carbon-12", "Carbon-13", "Carbon-14 (half-life ~5730 yrs)", "Carbon-15"],
    correctIndex: 2,
    explanation: "Carbon-14 is a radioactive beta-emitter created in the upper atmosphere, decaying with a half-life of 5,730 years.",
    difficulty: "easy",
  },
  {
    id: "chem-13",
    subject: "Chemistry",
    topic: "Biomolecules",
    question: "The alpha-helix and beta-pleated sheet secondary structures of proteins are stabilized by:",
    options: ["Disulfide covalent bonds", "Hydrogen bonds along polypeptide backbone", "Hydrophobic interactions", "Ionic salt bridges"],
    correctIndex: 1,
    explanation: "Secondary structure is stabilized by hydrogen bonding between the carbonyl oxygen (C=O) and amino hydrogen (N-H) of the peptide backbone.",
    difficulty: "easy",
  },
  {
    id: "chem-14",
    subject: "Chemistry",
    topic: "Solid State",
    question: "What is the coordination number of atoms in a face-centered cubic (FCC) crystal lattice?",
    options: ["6", "8", "12", "14"],
    correctIndex: 2,
    explanation: "In an FCC / cubic close-packed lattice, each sphere touches 12 nearest neighbors (6 in its plane, 3 above, 3 below).",
    difficulty: "medium",
  },
  {
    id: "chem-15",
    subject: "Chemistry",
    topic: "Spectroscopy",
    question: "Infrared (IR) spectroscopy detects transitions between:",
    options: ["Electronic energy levels", "Nuclear spin states", "Molecular vibrational energy levels", "Rotational states only"],
    correctIndex: 2,
    explanation: "Absorption of IR radiation causes transitions between quantized vibrational energy levels in covalent chemical bonds.",
    difficulty: "easy",
  },
  {
    id: "chem-16",
    subject: "Chemistry",
    topic: "Electrochemistry",
    question: "How many Faradays of electrical charge are required to electroplate 1 mole of aluminum from Al³⁺ ions?",
    options: ["1 F", "2 F", "3 F (~289,500 Coulombs)", "6 F"],
    correctIndex: 2,
    explanation: "Reduction Al³⁺ + 3e⁻ → Al requires 3 moles of electrons, which equals 3 Faradays (3 * 96,485 C).",
    difficulty: "easy",
  },

  // ─── BIOLOGY (16 Questions) ───
  {
    id: "bio-1",
    subject: "Biology",
    topic: "Cellular Respiration",
    question: "What is the final electron acceptor in the mitochondrial electron transport chain during aerobic respiration?",
    options: ["NAD+", "FAD", "Oxygen (O₂)", "Cytochrome c"],
    correctIndex: 2,
    explanation: "Molecular oxygen acts as the terminal electron acceptor, combining with electrons and protons at complex IV to form water (H₂O).",
    difficulty: "easy",
  },
  {
    id: "bio-2",
    subject: "Biology",
    topic: "Molecular Genetics",
    question: "During DNA replication, which enzyme is responsible for unwinding the double helix at the replication fork?",
    options: ["DNA Polymerase III", "DNA Helicase", "Topoisomerase (Gyrase)", "DNA Ligase"],
    correctIndex: 1,
    explanation: "DNA Helicase breaks the hydrogen bonds between complementary base pairs, unwinding double-stranded DNA into two single template strands.",
    difficulty: "easy",
  },
  {
    id: "bio-3",
    subject: "Biology",
    topic: "Photosynthesis",
    question: "In the light-dependent reactions of photosynthesis, photolysis of water directly produces electrons to replace those lost by:",
    options: ["Photosystem I (P700)", "Photosystem II (P680)", "ATP Synthase", "Rubisco enzyme"],
    correctIndex: 1,
    explanation: "Photosystem II's reaction center P680 becomes strongly oxidized after photoexcitation and is replenished by electrons from water splitting: 2H₂O → 4H⁺ + 4e⁻ + O₂.",
    difficulty: "medium",
  },
  {
    id: "bio-4",
    subject: "Biology",
    topic: "Genetics",
    question: "In a dihybrid cross of two heterozygous individuals (AaBb × AaBb), what is the expected phenotypic ratio under independent assortment?",
    options: ["1:2:1", "3:1", "9:3:3:1", "1:1:1:1"],
    correctIndex: 2,
    explanation: "Mendelian independent assortment predicts a 9:3:3:1 phenotypic ratio (9 dominant/dominant, 3 dominant/recessive, 3 recessive/dominant, 1 recessive/recessive).",
    difficulty: "easy",
  },
  {
    id: "bio-5",
    subject: "Biology",
    topic: "Immunology",
    question: "Which antibody isotype is the first to be secreted during a primary immune response and exists predominantly as a pentamer?",
    options: ["IgG", "IgA", "IgM", "IgE"],
    correctIndex: 2,
    explanation: "IgM is the initial immunoglobulin produced upon first encounter with an antigen, forming a high-avidity pentameric structure with 10 antigen binding sites.",
    difficulty: "medium",
  },
  {
    id: "bio-6",
    subject: "Biology",
    topic: "Neurobiology",
    question: "The rapid depolarization phase of a neuronal action potential is primarily driven by the influx of which ion?",
    options: ["Potassium (K⁺)", "Sodium (Na⁺)", "Calcium (Ca²⁺)", "Chloride (Cl⁻)"],
    correctIndex: 1,
    explanation: "Threshold depolarization opens voltage-gated Na⁺ channels, causing massive Na⁺ influx down its electrochemical gradient.",
    difficulty: "easy",
  },
  {
    id: "bio-7",
    subject: "Biology",
    topic: "Cell Biology",
    question: "Which organelle contains hydrolytic enzymes responsible for autophagy and degrading cellular waste?",
    options: ["Peroxisome", "Lysosome", "Golgi Apparatus", "Endoplasmic Reticulum"],
    correctIndex: 1,
    explanation: "Lysosomes contain acid hydrolases that function at pH ~4.5-5.0 to break down biomolecules, damaged organelles, and engulfed pathogens.",
    difficulty: "easy",
  },
  {
    id: "bio-8",
    subject: "Biology",
    topic: "Gene Expression",
    question: "In eukaryotic mRNA processing, what modifications are added before export from the nucleus?",
    options: ["5' m7G cap and 3' poly-A tail with intron splicing", "Operon promoter binding and poly-G tail", "Ribosomal methylation and exon excision", "Histone acetylation only"],
    correctIndex: 0,
    explanation: "Pre-mRNA undergoes 5' 7-methylguanosine capping, spliceosome removal of introns, and addition of a 3' polyadenylation tail.",
    difficulty: "medium",
  },
  {
    id: "bio-9",
    subject: "Biology",
    topic: "Endocrinology",
    question: "Insulin is secreted by which specific endocrine cells in the pancreas?",
    options: ["Alpha cells", "Beta cells of Islets of Langerhans", "Delta cells", "Acinar exocrine cells"],
    correctIndex: 1,
    explanation: "Beta cells located within the pancreatic Islets of Langerhans synthesize and secrete insulin in response to elevated blood glucose.",
    difficulty: "easy",
  },
  {
    id: "bio-10",
    subject: "Biology",
    topic: "Ecology",
    question: "According to Lindeman's 10% rule in trophic ecology, what happens to the remaining ~90% of energy at each trophic transfer?",
    options: ["Converted into mineral biomass", "Lost primarily as metabolic heat, respiration, and unconsumed waste", "Stored permanently in soil humus", "Recycled by carnivores"],
    correctIndex: 1,
    explanation: "Approximately 90% of energy is expended through cellular respiration, metabolic heat loss, and incomplete digestion/egestion.",
    difficulty: "easy",
  },
  {
    id: "bio-11",
    subject: "Biology",
    topic: "Evolution",
    question: "The Hardy-Weinberg equilibrium principle requires which of the following conditions to maintain constant allele frequencies?",
    options: ["Small population size and assortative mating", "High mutation rate and directional selection", "Large population, random mating, and no migration or natural selection", "Continuous gene flow between neighboring demes"],
    correctIndex: 2,
    explanation: "Hardy-Weinberg equilibrium relies on 5 assumptions: infinitely large population, random mating, no mutation, no gene flow (migration), and no natural selection.",
    difficulty: "medium",
  },
  {
    id: "bio-12",
    subject: "Biology",
    topic: "Enzyme Kinetics",
    question: "A competitive enzyme inhibitor affects kinetic parameters by:",
    options: ["Decreasing Vmax while keeping Km constant", "Increasing apparent Km while leaving Vmax unchanged", "Decreasing both Vmax and Km", "Increasing Vmax"],
    correctIndex: 1,
    explanation: "Competitive inhibitors bind to the active site. High substrate concentration can outcompete the inhibitor, so Vmax is unchanged, but higher [S] is needed to reach 1/2 Vmax (Km increases).",
    difficulty: "hard",
  },
  {
    id: "bio-13",
    subject: "Biology",
    topic: "Cardiovascular Physiology",
    question: "The natural electrical pacemaker of the mammalian heart is the:",
    options: ["Atrioventricular (AV) Node", "Sinoatrial (SA) Node", "Bundle of His", "Purkinje Fibers"],
    correctIndex: 1,
    explanation: "The Sinoatrial (SA) node in the right atrium generates spontaneous autorhythmic action potentials at the highest rate (~60-100 bpm).",
    difficulty: "easy",
  },
  {
    id: "bio-14",
    subject: "Biology",
    topic: "Biotechnology",
    question: "CRISPR-Cas9 gene editing employs a guide RNA (gRNA) to direct the Cas9 endonuclease to introduce:",
    options: ["Single-stranded RNA degradation", "Targeted double-strand DNA breaks", "Telomere elongation", "Ribosomal frameshifts"],
    correctIndex: 1,
    explanation: "Cas9 uses the guide RNA sequence to find complementary genomic DNA and creates a precise double-stranded break adjacent to a PAM motif.",
    difficulty: "medium",
  },
  {
    id: "bio-15",
    subject: "Biology",
    topic: "Embryology",
    question: "The human nervous system and epidermis develop from which embryonic germ layer?",
    options: ["Endoderm", "Mesoderm", "Ectoderm", "Neural Crest only"],
    correctIndex: 2,
    explanation: "The ectoderm gives rise to the nervous system (brain, spinal cord, nerves), epidermis of the skin, hair, and nails.",
    difficulty: "medium",
  },
  {
    id: "bio-16",
    subject: "Biology",
    topic: "Botany",
    question: "In vascular plants, transport of sucrose and organic nutrients through the phloem is best explained by:",
    options: ["Cohesion-tension theory", "Münch pressure-flow hypothesis", "Capillary action", "Root pressure osmosis"],
    correctIndex: 1,
    explanation: "Ernst Münch's pressure-flow hypothesis describes active loading of sucrose into sieve tubes creating high turgor pressure that drives bulk flow toward sugar sinks.",
    difficulty: "hard",
  },

  // ─── WORLD HISTORY & LITERATURE (16 Questions) ───
  {
    id: "hist-1",
    subject: "World History",
    topic: "Ancient Civilizations",
    question: "The Code of Hammurabi, one of the earliest deciphered legal codes in history, originated in which civilization?",
    options: ["Ancient Egypt", "Babylonia (Mesopotamia)", "Persian Empire", "Indus Valley"],
    correctIndex: 1,
    explanation: "King Hammurabi of Babylon enacted his legal code around 1754 BCE, inscribed on diorite stelae and clay tablets ('an eye for an eye').",
    difficulty: "easy",
  },
  {
    id: "hist-2",
    subject: "World History",
    topic: "European History",
    question: "The Peace of Westphalia (1648) concluded which devastating conflict and established the modern concept of sovereign statehood?",
    options: ["The Hundred Years' War", "The Thirty Years' War", "The War of Spanish Succession", "The Napoleonic Wars"],
    correctIndex: 1,
    explanation: "The 1648 treaties ended the Thirty Years' War in the Holy Roman Empire, enshrining the principle of state sovereignty ('Westphalian sovereignty').",
    difficulty: "medium",
  },
  {
    id: "hist-3",
    subject: "World History",
    topic: "World War I",
    question: "The assassination of Archduke Franz Ferdinand in 1914, which triggered World War I, occurred in:",
    options: ["Vienna", "Sarajevo", "Belgrade", "Prague"],
    correctIndex: 1,
    explanation: "Gavrilo Princip, a member of the Black Hand nationalist group, assassinated Archduke Franz Ferdinand in Sarajevo, Bosnia on June 28, 1914.",
    difficulty: "easy",
  },
  {
    id: "hist-4",
    subject: "World History",
    topic: "Philosophy & Enlightenment",
    question: "Which Enlightenment philosopher argued for the 'separation of powers' into legislative, executive, and judicial branches in 'The Spirit of the Laws'?",
    options: ["Voltaire", "Jean-Jacques Rousseau", "Baron de Montesquieu", "John Locke"],
    correctIndex: 2,
    explanation: "Montesquieu published 'De l'esprit des lois' in 1748, heavily inspiring the checks and balances architecture of modern democratic constitutions.",
    difficulty: "medium",
  },
  {
    id: "hist-5",
    subject: "World History",
    topic: "Renaissance & Science",
    question: "The printing press with movable metal type was introduced to Europe around 1440 by:",
    options: ["Leonardo da Vinci", "Johannes Gutenberg", "Desiderius Erasmus", "William Caxton"],
    correctIndex: 1,
    explanation: "Johannes Gutenberg in Mainz, Germany invented the movable-type printing press, sparking the information revolution across Europe.",
    difficulty: "easy",
  },
  {
    id: "hist-6",
    subject: "World History",
    topic: "Asian History",
    question: "The Silk Road reached its height of security and administrative efficiency during which empire that established the 'Pax Mongolica'?",
    options: ["Tang Dynasty", "Mongol Empire", "Ottoman Empire", "Mughal Empire"],
    correctIndex: 1,
    explanation: "The Mongol Empire unified Eurasian trade routes across China, Central Asia, and Persia under the Pax Mongolica during the 13th and 14th centuries.",
    difficulty: "easy",
  },
  {
    id: "hist-7",
    subject: "World History",
    topic: "20th Century History",
    question: "The policy of 'Perestroika' (restructuring) and 'Glasnost' (openness) was introduced in the Soviet Union by:",
    options: ["Nikita Khrushchev", "Leonid Brezhnev", "Mikhail Gorbachev", "Boris Yeltsin"],
    correctIndex: 2,
    explanation: "General Secretary Mikhail Gorbachev initiated Glasnost and Perestroika in the mid-1980s to reform economic stagnancy, preceding the 1991 Soviet dissolution.",
    difficulty: "easy",
  },
  {
    id: "hist-8",
    subject: "World History",
    topic: "Industrial Revolution",
    question: "James Watt's major contribution to the Industrial Revolution in 1769 was:",
    options: ["The Spinning Jenny", "The separate condenser for the steam engine", "The Bessemer steel converter", "The telegraph"],
    correctIndex: 1,
    explanation: "James Watt patented the separate condenser for Newcomen's atmospheric engine, dramatically improving thermal efficiency and fueling industrial expansion.",
    difficulty: "medium",
  },
  {
    id: "hist-9",
    subject: "World History",
    topic: "Literary Theory",
    question: "What literary device is used when an author places two contrasting concepts or characters side by side to highlight their differences?",
    options: ["Alliteration", "Juxtaposition", "Hyperbole", "Synecdoche"],
    correctIndex: 1,
    explanation: "Juxtaposition places two elements close together to emphasize comparative contrast, irony, or dramatic tension.",
    difficulty: "easy",
  },
  {
    id: "hist-10",
    subject: "World History",
    topic: "Classical Literature",
    question: "Which Greek tragedy by Sophocles deals with a hero who unwittingly kills his father and marries his mother?",
    options: ["Antigone", "Oedipus Rex", "Medea", "Prometheus Bound"],
    correctIndex: 1,
    explanation: "Sophocles' 'Oedipus Rex' explores tragic fate, hubris, and dramatic irony through the story of Oedipus, King of Thebes.",
    difficulty: "easy",
  },
  {
    id: "hist-11",
    subject: "World History",
    topic: "Decolonization",
    question: "The 1955 Bandung Conference was a milestone in international diplomacy that paved the way for the creation of:",
    options: ["The United Nations Security Council", "The Non-Aligned Movement (NAM)", "The European Union", "The Warsaw Pact"],
    correctIndex: 1,
    explanation: "Organized by Asian and African leaders in Indonesia, the Bandung Conference opposed colonialism and created the foundation for the Non-Aligned Movement during the Cold War.",
    difficulty: "hard",
  },
  {
    id: "hist-12",
    subject: "World History",
    topic: "American History",
    question: "The Emancipation Proclamation issued by President Abraham Lincoln in 1863 declared free all enslaved people:",
    options: ["Everywhere in all US territories and border states", "Exclusively in the Confederate states currently in rebellion against the Union", "Only in Washington D.C.", "Only those who enlisted in the Union Navy"],
    correctIndex: 1,
    explanation: "Issued as a wartime executive measure, the Proclamation specifically applied to the 10 Confederate states in active rebellion against the federal government.",
    difficulty: "medium",
  },
  {
    id: "hist-13",
    subject: "World History",
    topic: "Middle Eastern History",
    question: "The House of Wisdom (Bayt al-Hikmah), a famous intellectual academy and library during the Islamic Golden Age, was located in:",
    options: ["Cairo", "Damascus", "Baghdad", "Cordoba"],
    correctIndex: 2,
    explanation: "Founded by Abbasid Caliph Harun al-Rashid in Baghdad, the House of Wisdom was a major center for translating and expanding Greek, Persian, and Indian scientific texts.",
    difficulty: "medium",
  },
  {
    id: "hist-14",
    subject: "World History",
    topic: "Literature",
    question: "George Orwell's political allegorical novella 'Animal Farm' reflects events leading up to and during:",
    options: ["The French Revolution of 1789", "The Russian Revolution of 1917 and Stalinist era", "The Spanish Civil War", "The American Civil War"],
    correctIndex: 1,
    explanation: "The animal characters directly satirize figures and events of the 1917 Bolshevik Revolution and the rise of totalitarian Stalinism (Napoleon represents Stalin, Snowball is Trotsky).",
    difficulty: "easy",
  },
  {
    id: "hist-15",
    subject: "World History",
    topic: "Maritime Exploration",
    question: "The first expedition to successfully circumnavigate the Earth (1519–1522) was initiated under the command of:",
    options: ["Christopher Columbus", "Ferdinand Magellan (completed by Juan Sebastián Elcano)", "Vasco da Gama", "Francis Drake"],
    correctIndex: 1,
    explanation: "Ferdinand Magellan led the Spanish expedition; although he died in the Philippines in 1521, Juan Sebastián Elcano completed the circumnavigation on the ship Victoria.",
    difficulty: "easy",
  },
  {
    id: "hist-16",
    subject: "World History",
    topic: "French Revolution",
    question: "The period known as the 'Reign of Terror' (1793–1794) during the French Revolution was led by the Committee of Public Safety under:",
    options: ["Georges Danton", "Maximilien Robespierre", "Napoleon Bonaparte", "Jean-Paul Marat"],
    correctIndex: 1,
    explanation: "Robespierre directed the Committee of Public Safety, executing thousands by guillotine before his own downfall in the Thermidorian Reaction of July 1794.",
    difficulty: "easy",
  },
];
